// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4DjNxp1_fk14zvnwBPj5h--ccjyFa5CY',
    appId: '1:999560377871:web:ed9cdea4841078ad75157a',
    messagingSenderId: '999560377871',
    projectId: 'traveler-6ea4c',
    authDomain: 'traveler-6ea4c.firebaseapp.com',
    storageBucket: 'traveler-6ea4c.firebasestorage.app',
    measurementId: 'G-XQ7DESMRS2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHylfBQv7DnWyIA6MTtJ8ahl9oEFuBB4M',
    appId: '1:999560377871:android:1752f49da71da2f375157a',
    messagingSenderId: '999560377871',
    projectId: 'traveler-6ea4c',
    storageBucket: 'traveler-6ea4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB88KEVxcK3ZL7w1qeGaw2pglxieuva-Ko',
    appId: '1:999560377871:ios:b3406e4a34c6d81e75157a',
    messagingSenderId: '999560377871',
    projectId: 'traveler-6ea4c',
    storageBucket: 'traveler-6ea4c.firebasestorage.app',
    iosBundleId: 'com.example.traveler',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB88KEVxcK3ZL7w1qeGaw2pglxieuva-Ko',
    appId: '1:999560377871:ios:b3406e4a34c6d81e75157a',
    messagingSenderId: '999560377871',
    projectId: 'traveler-6ea4c',
    storageBucket: 'traveler-6ea4c.firebasestorage.app',
    iosBundleId: 'com.example.traveler',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4DjNxp1_fk14zvnwBPj5h--ccjyFa5CY',
    appId: '1:999560377871:web:2e769f79b05453e175157a',
    messagingSenderId: '999560377871',
    projectId: 'traveler-6ea4c',
    authDomain: 'traveler-6ea4c.firebaseapp.com',
    storageBucket: 'traveler-6ea4c.firebasestorage.app',
    measurementId: 'G-S53WJG63XF',
  );

}